version: '3.2'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    network_mode: bridge
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - DEFAULT_REGION=sa-east-1
    volumes:
      - './.localstack:/var/lib/localstack'
