version: '3.2'
services:
  localstack:
    image: localstack/localstack-full
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      
      
#version: '3'
#services:
#  localstack:
#    image: localstack/localstack-light
#    ports:
#      - "4566:4566"
#    environment:
#      - DEBUG=1
#      - DEFAULT_REGION=sa-east-1
#      - SERVICES=sqs,dynamodb
#      - SERVICES=sqs,dynamodb,s3,kms,events,sts,iam
